package com.example.cbs_mvp;

import static org.assertj.core.api.Assertions.assertThat;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

import com.example.cbs_mvp.candidate.CandidateController;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class SmokeTest {

    @LocalServerPort
    private int port;

    @Autowired
    private CandidateController candidateController;

    @Test
    void contextLoads() {
        assertThat(candidateController).isNotNull();
    }

    @Test
    void mainPageLoads() throws Exception {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:" + port + "/"))
                .build();

        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        assertThat(response.statusCode()).isEqualTo(200);
        assertThat(response.body()).contains("CBS-MVP Dashboard");

        // Save the evidence (HTML Snapshot)
        java.nio.file.Files.writeString(
                java.nio.file.Paths.get("smoke_test_evidence.html"),
                "<!-- GENERATED BY SMOKE TEST -->\n" + response.body());
    }

    @Test
    void fxRateEndpointIsAccessible() throws Exception {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:" + port + "/fx/rate"))
                .build();

        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        // Might return 200 or 401/403 depending on security, but as long as it
        // reachable (not 404/500), it's verified.
        assertThat(response.statusCode()).isLessThan(500);
    }
}
